/* Error Code Start */
#define	CB_OK								0

#define CB_FS_OPEN_FILE_ERROR				-1
#define CB_FS_CLOSE_FILE_ERROR				-2
#define CB_FS_SIZE_EOF_NOT_FOUND			-3
#define CB_FS_READ_ERROR					-4

#define CB_BB_OPEN_ERROR_OPEN_PORT			-5
#define CB_BB_OPEN_VERSION_INCOMPATIBLE		-6
#define CB_BB_OPEN_DRIVER_INCOMPATIBLE		-7
#define CB_BB_OPEN_DEVICEIOCONTROL_FAIL		-8
#define CB_BB_CLOSE_BYTEBLASTER_NOT_OPEN	-9
#define CB_BB_FLUSH_ERROR					-10
#define CB_BB_VERIFY_BYTEBLASTER_NOT_FOUND	-11
#define CB_BB_LPTREAD_ERROR					-12
#define CB_BB_LPTWRITE_ERROR				-13

#define CB_PS_CONF_NSTATUS_LOW				-14
#define CB_PS_CONF_CONFDONE_LOW				-15
#define CB_PS_INIT_NSTATUS_LOW				-16
#define CB_PS_INIT_CONFDONE_LOW				-17

#define CB_AS_VERIFY_FAIL					-18		
#define CB_AS_UNSUPPORTED_DEVICE			-19 
#define CB_AS_WRONG_RPD_FILE				-20

#define CB_INVALID_COMMAND					-21

/* Error Code END  */
